{
 "title": "NGINX",
 "description": "Official dashboard for NGINX Prometheus exporter",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "fqdn", "query": "label_values(nginx_up, fqdn)" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX Status for $fqdn",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "repeat": "fqdn",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_up{fqdn=~\"$fqdn\"}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{fqdn=~\"$fqdn\"}[5m])",
     "legendFormat": "{{fqdn}} accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{fqdn=~\"$fqdn\"}[5m])",
     "legendFormat": "{{fqdn}} handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}} active"
    },
    {
     "expr": "nginx_connections_reading{fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}} reading"
    },
    {
     "expr": "nginx_connections_waiting{fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}} waiting"
    },
    {
     "expr": "nginx_connections_writing{fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}} writing"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{fqdn=~\"$fqdn\"}[5m])",
     "legendFormat": "{{fqdn}} total requests"
    }
   ]
  }
 ]
}