{
 "title": "Fluentd Metrics dashboard ",
 "description": "A quick dashboard for displaying Fluentd metrics. (uses Prometheus exporter)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Fluentd pods per cluster",
   "type": "gauge",
   "description": "Available pods of fluent running lumberjack",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{exported_namespace=~\"lumberjack-logging\"}",
     "legendFormat": "{{prometheus}}"
    }
   ]
  },
  {
   "title": "Pods in failure per cluster",
   "type": "gauge",
   "description": "Pods of fluent running lumberjack that are unavailable",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_unavailable{exported_namespace=~\"lumberjack-logging\"}",
     "legendFormat": "{{prometheus}}"
    }
   ]
  },
  {
   "title": "Lumberjack HTTP counter",
   "type": "graph",
   "description": "Counts The number of get, put and post operations from the logs ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "logsgenerator_verb_counter" }
   ]
  }
 ]
}