{
 "title": "Servers",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "project", "query": { "query": "label_values(project)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({project=~\"$project\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{project=~\"$project\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{project=~\"$project\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{project=~\"$project\",instance=~\"$instance\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{project=~\"$project\",instance=~\"$instance\"} / (node_memory_MemTotal_bytes{project=~\"$project\",instance=~\"$instance\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{project=~\"$project\",instance=~\"$instance\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {project=~\"$project\",instance=~\"$instance\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{project=~\"$project\",instance=~\"$instance\"} / node_memory_SwapTotal_bytes{project=~\"$project\",instance=~\"$instance\"})) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{project=~\"$project\",instance=~\"$instance\"}",
     "legendFormat": "filefd_{{instance}}"
    },
    {
     "expr": "irate(node_context_switches_total{project=~\"$project\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "switches_{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{project=~\"$project\",instance=~\"$instance\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU IOwait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{project=~\"$project\",instance=~\"$instance\",mode=\"iowait\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic(EXT4/XFS)",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{project=~\"$project\",instance=~'$instance',fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {project=~\"$project\",instance=~'$instance',fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{project=~\"$project\",instance=~'$instance',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{project=~\"$project\",instance=~'$instance',fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Load / CPU / Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{project=~\"$project\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}_1m"
      },
      {
       "expr": "node_load5{project=~\"$project\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}_5m"
      },
      {
       "expr": "node_load15{project=~\"$project\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}_15m"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{project=~\"$project\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}_Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{project=~\"$project\",instance=~\"$instance\"} - node_memory_MemAvailable_bytes{project=~\"$project\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}_Used"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{project=~\"$project\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}_Avaliable"
      }
     ]
    },
    {
     "title": "CPU Basic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{project=~\"$project\",instance=~\"$instance\",mode=\"system\"}[30m])) by (instance)",
       "legendFormat": "{{instance}}_System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{project=~\"$project\",instance=~\"$instance\",mode=\"user\"}[30m])) by (instance)",
       "legendFormat": "{{instance}}_User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{project=~\"$project\",instance=~\"$instance\",mode=\"iowait\"}[30m])) by (instance)",
       "legendFormat": "{{instance}}_Iowait"
      },
      {
       "expr": "1 - avg(irate(node_cpu_seconds_total{project=~\"$project\",instance=~\"$instance\",mode=\"idle\"}[30m])) by (instance)",
       "legendFormat": "{{instance}}_Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used Basic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1-(node_filesystem_free_bytes{project=~\"$project\",instance=~'$instance',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{project=~\"$project\",instance=~'$instance',fstype=~\"ext4|xfs\"})",
       "legendFormat": "{{instance}}：{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Time Spent Doing I/Os",
     "type": "timeseries",
     "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{project=~\"$project\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{instance}}_{{device}}_ IO time"
      }
     ]
    },
    {
     "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
     "type": "timeseries",
     "description": "Time spent on each read/write operation",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{project=~\"$project\",instance=~\"$instance\"}[$__interval]) / irate(node_disk_reads_completed_total{project=~\"$project\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{instance}}_{{device}}_Read time"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{project=~\"$project\",instance=~\"$instance\"}[$__interval]) / irate(node_disk_writes_completed_total{project=~\"$project\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{instance}}_{{device}}_Write time"
      }
     ]
    },
    {
     "title": "Disk IOps Completed",
     "type": "timeseries",
     "description": "Read/write completions per second",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{project=~\"$project\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{instance}}_{{device}}_Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{project=~\"$project\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{instance}}_{{device}}_Writes completed"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "timeseries",
     "description": "Per second read / write bytes ",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{project=~\"$project\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{instance}}_{{device}}_Read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{project=~\"$project\",instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{instance}}_{{device}}_Written bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic Basic",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{project=~\"$project\",instance=~'$instance',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
       "legendFormat": "{{instance}}_{{device}}_receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{project=~\"$project\",instance=~'$instance',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
       "legendFormat": "{{instance}}_{{device}}_transmit"
      }
     ]
    },
    {
     "title": "Network Sockstat",
     "type": "timeseries",
     "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{project=~\"$project\",instance=~'$instance'}",
       "legendFormat": "{{instance}}_CurrEstab"
      },
      {
       "expr": "node_sockstat_TCP_tw{project=~\"$project\",instance=~'$instance'}",
       "legendFormat": "{{instance}}_TCP_tw"
      },
      {
       "expr": "node_sockstat_sockets_used{project=~\"$project\",instance=~'$instance'}",
       "legendFormat": "{{instance}}_Sockets_used"
      },
      {
       "expr": "node_sockstat_UDP_inuse{project=~\"$project\",instance=~'$instance'}",
       "legendFormat": "{{instance}}_UDP_inuse"
      },
      {
       "expr": "node_sockstat_TCP_alloc{project=~\"$project\",instance=~'$instance'}",
       "legendFormat": "{{instance}}_TCP_alloc"
      }
     ]
    }
   ]
  }
 ]
}