apiVersion: 1

datasources:
  - name: Mimir
    uid: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://mimir.service.consul:9009/prometheus
    version: 1
    basicAuth: false
    isDefault: true
    editable: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      alertmanagerUid: "alertmanager"
    secureJsonData:
      httpHeaderValue1: "demo"
  - name: Mimir Alertmanager
    uid: alertmanager
    type: alertmanager
    access: proxy
    orgId: 1
    url: http://mimir.service.consul:9009/
    version: 1
    editable: true
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      implementation: "cortex"
    secureJsonData:
      httpHeaderValue1: "demo"
  - name: "Loki"
    type: "loki"
    access: "proxy"
    url: "http://loki.service.consul:3100"
    basicAuth: false
    isDefault: false
    editable: false