apiVersion: 1
deleteDatasources: []
datasources:
  - name: "mimir"
    type: "prometheus"
    access: "proxy"
    url: "http://mimir.service.consul:8080/prometheus"
    basicAuth: false
    isDefault: true
    editable: false
    uid: mimir
    secureJsonData:
      httpHeaderValue1: 'X-Scope-OrgID'
      httpHeaderValue2: demo
  - name: Mimir Alertmanager
    uid: alertmanager
    type: alertmanager
    access: proxy
    orgId: 1
    url: http://mimir.service.consul:8080/
    version: 1
    editable: true
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      implementation: "cortex"
    secureJsonData:
      httpHeaderValue1: demo
  - name: "Loki"
    type: "loki"
    access: "proxy"
    url: "http://loki.service.consul:3100"
    basicAuth: false
    isDefault: false
    editable: false