apiVersion: 1
deleteDatasources: []
  # - name: Prometheus
  #   orgId: 1
  # - name: prometheus
  #   orgId: 1

datasources:
  - name: "prometheus"
    type: "prometheus"
    access: "proxy"
    url: "http://prometheus.service.consul:9090"
    basicAuth: false
    isDefault: true
    editable: false
    uid: prometheus
  - name: "Metrics"
    type: "prometheus"
    access: "proxy"
    url: "http://prometheus.service.consul:9090"
    basicAuth: false
    isDefault: false
    editable: false
  - name: "Loki"
    type: "loki"
    access: "proxy"
    url: "http://loki.service.consul:3100"
    basicAuth: false
    isDefault: false
    editable: false