{
 "title": "Gitea",
 "description": "Monitor Gitea server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "project",
    "query": {
     "query": "label_values(gitea_build_info,project)"
    }
   },
   {
    "name": "fqdn",
    "query": {
     "query": "label_values(gitea_build_info{project=~\"$project\"},fqdn)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resident memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"gitea\",project=~\"$project\",fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"gitea\",project=~\"$project\",fqdn=~\"$fqdn\"}[$__interval])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Open FDS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"gitea\",project=~\"$project\",fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Number of Accesses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_accesses{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Number of Repositories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_repositories{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Number of Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_users{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Number of Issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_issues{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Number of Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_actions{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Number of Labels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_labels{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Number of Organizations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_organizations{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Number of Teams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_teams{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Number of Follows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_follows{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Number of PublicKeys",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_publickeys{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Number of Stars",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_stars{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Number of Webhooks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_webhooks{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Number of Releases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_releases{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Number of Comments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_comments{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Number of Milestones",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_milestones{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Number of Watches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_watches{project=~\"$project\",fqdn=~\"$fqdn\"}"
    }
   ]
  }
 ]
}