{
 "title": "Nomad",
 "description": "Nomad Jobs metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "project", "query": { "query": "label_values(project)" } },
   {
    "name": "datacenter",
    "label": "DC",
    "query": "label_values(nomad_client_uptime, datacenter)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(nomad_client_uptime{project=~\"$project\"},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Failed allocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nomad_client_allocs_failed{host=~\"$host\"} ",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Client allocations pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(nomad_client_allocations_pending{host=~\"$host\",host=~\"$host\"}) by(project, node_status)",
     "legendFormat": "{{project}} {{node_status}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage Percent from $project / $host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_cpu_total_percent{host=~\"$host\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "CPU total ticks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Total Ticks from $project / $host",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "timeticks" } },
     "targets": [
      {
       "expr": "avg(nomad_client_allocs_cpu_total_ticks{host=~\"$host\"}) by(exported_job, task)",
       "legendFormat": "{{task}}"
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Memory usage from $project / $host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_usage{host=~\"$host\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Memory cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Cache from $project / $host",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(nomad_client_allocs_memory_cache{host=~\"$host\"}) by(exported_job, task)",
       "legendFormat": "{{task}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RSS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 },
   "collapsed": true,
   "panels": [
    {
     "title": "RSS from $project / $host",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(nomad_client_allocs_memory_rss{host=~\"$host\"}) by(exported_job, task)",
       "legendFormat": "{{task}}"
      }
     ]
    }
   ]
  }
 ]
}