{
 "title": "NGINX (mimir)",
 "description": "Official dashboard for NGINX Prometheus exporter",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "fqdn", "query": "label_values(nginx_up, fqdn)" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NGINX Status for $fqdn",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "repeat": "fqdn",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{fqdn=~\"$fqdn\"}"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{fqdn=~\"$fqdn\"}[5m])",
     "legendFormat": "{{fqdn}} accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{fqdn=~\"$fqdn\"}[5m])",
     "legendFormat": "{{fqdn}} handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}} active"
    },
    {
     "expr": "nginx_connections_reading{fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}} reading"
    },
    {
     "expr": "nginx_connections_waiting{fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}} waiting"
    },
    {
     "expr": "nginx_connections_writing{fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}} writing"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{fqdn=~\"$fqdn\"}[5m])",
     "legendFormat": "{{fqdn}} total requests"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{filename=~\"/data/$fqdn/var/log/nginx/access.log\"}"
    }
   ]
  }
 ]
}